services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: unless-stopped
    env_file: ./app.env
    expose:
      - "3000"
    volumes:
      - ../public/uploads:/app/public/uploads
    networks: [web]

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      ADMIN_EMAIL_CERT: ${ADMIN_EMAIL_CERT:-admin@mro.bio}
    depends_on: [app]
    networks: [web]


volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge
