/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RendaextraRouteImport } from './routes/rendaextra'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedefinirSenhaTokenRouteImport } from './routes/redefinir-senha.$token'
import { Route as ObObrigadoRouteImport } from './routes/ob/obrigado'
import { Route as AtivarTokenRouteImport } from './routes/ativar.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicLocalImagesRouteImport } from './routes/api/public/local-images'
import { Route as ApiPublicCertCheckRouteImport } from './routes/api/public/cert-check'
import { Route as AuthenticatedSitesNovoRouteImport } from './routes/_authenticated/sites.novo'
import { Route as AuthenticatedSitesIdRouteImport } from './routes/_authenticated/sites.$id'
import { Route as ApiPublicWebhooksKiwifyRouteImport } from './routes/api/public/webhooks/kiwify'
import { Route as ApiPublicWebhooksInfinitepayRouteImport } from './routes/api/public/webhooks/infinitepay'
import { Route as ApiPublicSiteSlugRouteImport } from './routes/api/public/site/$slug'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'
import { Route as ApiPublicCronSubscriptionsRouteImport } from './routes/api/public/cron/subscriptions'
import { Route as ApiPublicCronEmailOutboxRouteImport } from './routes/api/public/cron/email-outbox'

const RendaextraRoute = RendaextraRouteImport.update({
  id: '/rendaextra',
  path: '/rendaextra',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaTokenRoute = RedefinirSenhaTokenRouteImport.update({
  id: '/redefinir-senha/$token',
  path: '/redefinir-senha/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ObObrigadoRoute = ObObrigadoRouteImport.update({
  id: '/ob/obrigado',
  path: '/ob/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarTokenRoute = AtivarTokenRouteImport.update({
  id: '/ativar/$token',
  path: '/ativar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLocalImagesRoute = ApiPublicLocalImagesRouteImport.update({
  id: '/api/public/local-images',
  path: '/api/public/local-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCertCheckRoute = ApiPublicCertCheckRouteImport.update({
  id: '/api/public/cert-check',
  path: '/api/public/cert-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesNovoRoute = AuthenticatedSitesNovoRouteImport.update({
  id: '/sites/novo',
  path: '/sites/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesIdRoute = AuthenticatedSitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksKiwifyRoute = ApiPublicWebhooksKiwifyRouteImport.update({
  id: '/api/public/webhooks/kiwify',
  path: '/api/public/webhooks/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksInfinitepayRoute =
  ApiPublicWebhooksInfinitepayRouteImport.update({
    id: '/api/public/webhooks/infinitepay',
    path: '/api/public/webhooks/infinitepay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSiteSlugRoute = ApiPublicSiteSlugRouteImport.update({
  id: '/api/public/site/$slug',
  path: '/api/public/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSubscriptionsRoute =
  ApiPublicCronSubscriptionsRouteImport.update({
    id: '/api/public/cron/subscriptions',
    path: '/api/public/cron/subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronEmailOutboxRoute =
  ApiPublicCronEmailOutboxRouteImport.update({
    id: '/api/public/cron/email-outbox',
    path: '/api/public/cron/email-outbox',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/rendaextra': typeof RendaextraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ativar/$token': typeof AtivarTokenRoute
  '/ob/obrigado': typeof ObObrigadoRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/sites/$id': typeof AuthenticatedSitesIdRoute
  '/sites/novo': typeof AuthenticatedSitesNovoRoute
  '/api/public/cert-check': typeof ApiPublicCertCheckRoute
  '/api/public/local-images': typeof ApiPublicLocalImagesRoute
  '/api/public/cron/email-outbox': typeof ApiPublicCronEmailOutboxRoute
  '/api/public/cron/subscriptions': typeof ApiPublicCronSubscriptionsRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/site/$slug': typeof ApiPublicSiteSlugRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/rendaextra': typeof RendaextraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ativar/$token': typeof AtivarTokenRoute
  '/ob/obrigado': typeof ObObrigadoRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/sites/$id': typeof AuthenticatedSitesIdRoute
  '/sites/novo': typeof AuthenticatedSitesNovoRoute
  '/api/public/cert-check': typeof ApiPublicCertCheckRoute
  '/api/public/local-images': typeof ApiPublicLocalImagesRoute
  '/api/public/cron/email-outbox': typeof ApiPublicCronEmailOutboxRoute
  '/api/public/cron/subscriptions': typeof ApiPublicCronSubscriptionsRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/site/$slug': typeof ApiPublicSiteSlugRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/administracao': typeof AdministracaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/rendaextra': typeof RendaextraRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/ativar/$token': typeof AtivarTokenRoute
  '/ob/obrigado': typeof ObObrigadoRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/_authenticated/sites/$id': typeof AuthenticatedSitesIdRoute
  '/_authenticated/sites/novo': typeof AuthenticatedSitesNovoRoute
  '/api/public/cert-check': typeof ApiPublicCertCheckRoute
  '/api/public/local-images': typeof ApiPublicLocalImagesRoute
  '/api/public/cron/email-outbox': typeof ApiPublicCronEmailOutboxRoute
  '/api/public/cron/subscriptions': typeof ApiPublicCronSubscriptionsRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/site/$slug': typeof ApiPublicSiteSlugRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/cadastro'
    | '/login'
    | '/rendaextra'
    | '/dashboard'
    | '/ativar/$token'
    | '/ob/obrigado'
    | '/redefinir-senha/$token'
    | '/sites/$id'
    | '/sites/novo'
    | '/api/public/cert-check'
    | '/api/public/local-images'
    | '/api/public/cron/email-outbox'
    | '/api/public/cron/subscriptions'
    | '/api/public/img/$'
    | '/api/public/site/$slug'
    | '/api/public/webhooks/infinitepay'
    | '/api/public/webhooks/kiwify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/cadastro'
    | '/login'
    | '/rendaextra'
    | '/dashboard'
    | '/ativar/$token'
    | '/ob/obrigado'
    | '/redefinir-senha/$token'
    | '/sites/$id'
    | '/sites/novo'
    | '/api/public/cert-check'
    | '/api/public/local-images'
    | '/api/public/cron/email-outbox'
    | '/api/public/cron/subscriptions'
    | '/api/public/img/$'
    | '/api/public/site/$slug'
    | '/api/public/webhooks/infinitepay'
    | '/api/public/webhooks/kiwify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/administracao'
    | '/cadastro'
    | '/login'
    | '/rendaextra'
    | '/_authenticated/dashboard'
    | '/ativar/$token'
    | '/ob/obrigado'
    | '/redefinir-senha/$token'
    | '/_authenticated/sites/$id'
    | '/_authenticated/sites/novo'
    | '/api/public/cert-check'
    | '/api/public/local-images'
    | '/api/public/cron/email-outbox'
    | '/api/public/cron/subscriptions'
    | '/api/public/img/$'
    | '/api/public/site/$slug'
    | '/api/public/webhooks/infinitepay'
    | '/api/public/webhooks/kiwify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdministracaoRoute: typeof AdministracaoRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RendaextraRoute: typeof RendaextraRoute
  AtivarTokenRoute: typeof AtivarTokenRoute
  ObObrigadoRoute: typeof ObObrigadoRoute
  RedefinirSenhaTokenRoute: typeof RedefinirSenhaTokenRoute
  ApiPublicCertCheckRoute: typeof ApiPublicCertCheckRoute
  ApiPublicLocalImagesRoute: typeof ApiPublicLocalImagesRoute
  ApiPublicCronEmailOutboxRoute: typeof ApiPublicCronEmailOutboxRoute
  ApiPublicCronSubscriptionsRoute: typeof ApiPublicCronSubscriptionsRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicSiteSlugRoute: typeof ApiPublicSiteSlugRoute
  ApiPublicWebhooksInfinitepayRoute: typeof ApiPublicWebhooksInfinitepayRoute
  ApiPublicWebhooksKiwifyRoute: typeof ApiPublicWebhooksKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rendaextra': {
      id: '/rendaextra'
      path: '/rendaextra'
      fullPath: '/rendaextra'
      preLoaderRoute: typeof RendaextraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha/$token': {
      id: '/redefinir-senha/$token'
      path: '/redefinir-senha/$token'
      fullPath: '/redefinir-senha/$token'
      preLoaderRoute: typeof RedefinirSenhaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ob/obrigado': {
      id: '/ob/obrigado'
      path: '/ob/obrigado'
      fullPath: '/ob/obrigado'
      preLoaderRoute: typeof ObObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar/$token': {
      id: '/ativar/$token'
      path: '/ativar/$token'
      fullPath: '/ativar/$token'
      preLoaderRoute: typeof AtivarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/local-images': {
      id: '/api/public/local-images'
      path: '/api/public/local-images'
      fullPath: '/api/public/local-images'
      preLoaderRoute: typeof ApiPublicLocalImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cert-check': {
      id: '/api/public/cert-check'
      path: '/api/public/cert-check'
      fullPath: '/api/public/cert-check'
      preLoaderRoute: typeof ApiPublicCertCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites/novo': {
      id: '/_authenticated/sites/novo'
      path: '/sites/novo'
      fullPath: '/sites/novo'
      preLoaderRoute: typeof AuthenticatedSitesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$id': {
      id: '/_authenticated/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof AuthenticatedSitesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/kiwify': {
      id: '/api/public/webhooks/kiwify'
      path: '/api/public/webhooks/kiwify'
      fullPath: '/api/public/webhooks/kiwify'
      preLoaderRoute: typeof ApiPublicWebhooksKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/infinitepay': {
      id: '/api/public/webhooks/infinitepay'
      path: '/api/public/webhooks/infinitepay'
      fullPath: '/api/public/webhooks/infinitepay'
      preLoaderRoute: typeof ApiPublicWebhooksInfinitepayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site/$slug': {
      id: '/api/public/site/$slug'
      path: '/api/public/site/$slug'
      fullPath: '/api/public/site/$slug'
      preLoaderRoute: typeof ApiPublicSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/subscriptions': {
      id: '/api/public/cron/subscriptions'
      path: '/api/public/cron/subscriptions'
      fullPath: '/api/public/cron/subscriptions'
      preLoaderRoute: typeof ApiPublicCronSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/email-outbox': {
      id: '/api/public/cron/email-outbox'
      path: '/api/public/cron/email-outbox'
      fullPath: '/api/public/cron/email-outbox'
      preLoaderRoute: typeof ApiPublicCronEmailOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSitesIdRoute: typeof AuthenticatedSitesIdRoute
  AuthenticatedSitesNovoRoute: typeof AuthenticatedSitesNovoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSitesIdRoute: AuthenticatedSitesIdRoute,
  AuthenticatedSitesNovoRoute: AuthenticatedSitesNovoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdministracaoRoute: AdministracaoRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RendaextraRoute: RendaextraRoute,
  AtivarTokenRoute: AtivarTokenRoute,
  ObObrigadoRoute: ObObrigadoRoute,
  RedefinirSenhaTokenRoute: RedefinirSenhaTokenRoute,
  ApiPublicCertCheckRoute: ApiPublicCertCheckRoute,
  ApiPublicLocalImagesRoute: ApiPublicLocalImagesRoute,
  ApiPublicCronEmailOutboxRoute: ApiPublicCronEmailOutboxRoute,
  ApiPublicCronSubscriptionsRoute: ApiPublicCronSubscriptionsRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicSiteSlugRoute: ApiPublicSiteSlugRoute,
  ApiPublicWebhooksInfinitepayRoute: ApiPublicWebhooksInfinitepayRoute,
  ApiPublicWebhooksKiwifyRoute: ApiPublicWebhooksKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
