// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Check for runtime environment variables (injected via window.ENV on VPS)
  // Fall back to import.meta.env for build-time variables
  // Fall back to process.env for server-side
  const runtimeEnv = typeof window !== 'undefined' ? (window as any).ENV : {};
  
  const rawUrl = runtimeEnv?.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || "";
  const rawKey = runtimeEnv?.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || "";

  const SUPABASE_URL = rawUrl.trim().replace(/\/$/, "");
  const SUPABASE_PUBLISHABLE_KEY = rawKey.trim();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Faltam variáveis do Supabase: ${missing.join(', ')}. Certifique-se de que o app.env está configurado na VPS.`;
    console.error(`[Supabase Client] ${message}`);
    // Only throw if we are in a browser and really need it
    if (typeof window !== 'undefined') {
      console.warn("Supabase client initializing with missing config. Authentication will likely fail.");
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY
      }
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

